
/*1*/
CREATE OR REPLACE PROCEDURE RECETAS_CON_MAS_ESTRELLAS 
IS 
	VAR_NOM_RECEPTA RECEPTA.NOM_RECEPTA%TYPE;
	VAR_XEF XEF.NOM_XEF%TYPE;
	VAR_DIFF RECEPTA.DIFICULTAT%TYPE;
BEGIN 
	SELECT NOM_RECEPTA,NOM_XEF , DIFICULTAT 
	INTO VAR_NOM_RECEPTA,VAR_XEF, VAR_DIFF 
	FROM RECEPTA r NATURAL JOIN XEF x ORDER BY DIFICULTAT DESC;
	DBMS_OUTPUT.PUT_LINE(VAR_NOM_RECEPTA || VAR_XEF || VAR_DIFF);
END;




BEGIN	
	RECETAS_CON_MAS_ESTRELLAS();
	DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;

