/*1*/
CREATE OR REPLACE PROCEDURE RECETAS_CON_MAS_ESTRELLAS 
IS 
	CURSOR RECEPTA_XEF_CURSOR IS
	SELECT * FROM RECEPTA NATURAL JOIN XEF ORDER BY DIFICULTAT DESC;
	VAR RECEPTA_XEF_CURSOR%ROWTYPE;
BEGIN
	OPEN RECEPTA_XEF_CURSOR;
	DBMS_OUTPUT.PUT_LINE('NOMBRE RECETA | NOMBRE XEF | DIFICULTAT');
	LOOP
		FETCH RECEPTA_XEF_CURSOR INTO VAR;
		EXIT WHEN RECEPTA_XEF_CURSOR%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(VAR.NOM_RECEPTA || ' | ' || VAR.NOM_XEF || ' | ' || VAR.DIFICULTAT);
	END LOOP;
	CLOSE RECEPTA_XEF_CURSOR;
END;



/*BLOQUE ANONIMO*/
BEGIN	
	/* EJERCICION 1:*/ 
	RECETAS_CON_MAS_ESTRELLAS();
	
END;
